routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('clients.create');
})->name('home');

Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('mlogin', 'Auth\LoginController@login')->name('mlogin');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::get('create/{client_id}/{process_id}/{step_id}', ['as' => 'messages.client', 'uses' => 'MessagesController@client_create']);
    Route::get('create/{client_id}/{related_party_id}', ['as' => 'messages.relatedparty', 'uses' => 'MessagesController@relatedparty_create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

Route::get('powerpoint', 'ReportController@powerpoint')->name('powerpoint');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('profile/{user?}', 'UserController@profile')->name('profile');
Route::get('settings', 'UserController@settings')->name('settings');
Route::post('settings/password', 'UserController@handlePassword')->name('settings.password');
Route::post('settings/profile', 'UserController@handleProfile')->name('settings.profile');
Route::post('settings/notifications', 'UserController@handleNotifications')->name('settings.notifications');

Route::any('/', 'ClientController@create')->name('home');
Route::any('/home', 'HomeController@index');
Route::get('recents', 'HomeController@recents')->name('recents');
Route::any('dashboard', 'HomeController@dashboard')->name('dashboard');
Route::any('progress', 'HomeController@progress')->name('progress');
Route::get('calendar', 'HomeController@calendar')->name('calendar');
Route::get('help', 'HelpController@create')->name('help.create');
Route::post('help', 'HelpController@store')->name('help.store');

Route::resource('emaillogs', 'EmailLogsController');
Route::get('emaillogs/{email_id}', 'EmailLogsController@show')->name('emaillogs.show');

Route::get('storage/crf', 'AssetController@getCrf')->name('crf_client');
Route::get('storage/avatar', 'AssetController@getAvatar')->name('avatar');
Route::get('storage/document', 'AssetController@getDocument')->name('document');
Route::get('storage/template', 'AssetController@getTemplate')->name('template');

Route::get('clients/amlreviewed', 'ClientController@amlReviewed')->name('clients.amlreviewed');
Route::get('clients/amlapproved', 'ClientController@amlApproved')->name('clients.amlapproved');
Route::get('clients/amlreviewedandapproved', 'ClientController@amlReviewedAndApproved')->name('clients.amlreviewedandapproved');
Route::get('clients/completed/{step_id}', 'ClientController@completed')->name('clients.completed');

Route::get('clients/xlsexport','ClientController@xlsExport')->name('clients.xlsexport');
Route::resource('clients', 'ClientController');
Route::post('clients/create','ClientController@create')->name('clients.create');
Route::get('clients/{client}/progress','ClientController@progress')->name('clients.progress');
Route::post('clients/{client}/progress','ClientController@storeProgress')->name('clients.storeprogress');
Route::post('clients/{client}/actions','ClientController@storeActions')->name('clients.storeactions');
Route::post('clients/{client}/progress/{process?}/{step?}','ClientController@completeStep')->name('clients.completestep');
Route::post('clients/{client}/progress2/{process?}/{step?}','ClientController@completeStep2')->name('clients.completestep2');
Route::get('clients/{client}/progress/{process}/{step}','ClientController@stepProgress')->name('clients.stepprogress');
Route::get('clients/{client}/progressaction/{process}/{step}/{action_id}','ClientController@stepProgressAction')->name('clients.stepprogressaction');
Route::get('clients/{client}/documents/{process}/{step}','ClientController@documents')->name('clients.documents');
Route::get('clients/{client}/forms','ClientController@forms')->name('clients.forms');
Route::get('clients/{client}/edit/{process}/{step}','ClientController@edit')->name('clients.edit');
Route::get('clients/{client}/forms/uploadform','ClientController@uploadforms')->name('forms.uploadforms');
Route::get('clients/{client}/forms/editform/{formid}','ClientController@edituploadforms')->name('forms.editforms');
Route::post('clients/{client}/forms/storeform','ClientController@storeuploadforms')->name('forms.uploadstore');
Route::post('clients/{clientid}/forms/{formid}/formupdate','ClientController@updateuploadforms')->name('forms.formupdate');
Route::get('clients/{client}/forms/createcrf','ClientController@createCrfForm')->name('forms.createcrf');
Route::get('clients/{client}/forms/editcrf/{formid}','ClientController@editCrfForm')->name('forms.editcrf');
Route::get('clients/{client}/forms/signcrf/{formid}','ClientController@signCrfForm')->name('forms.signcrf');
Route::post('clients/{clientid}/forms/{formid}/updatecrf','ClientController@updateCrfForm')->name('forms.updatecrf');
Route::post('clients/{client}/forms/storecrf','ClientController@saveCrfForm')->name('forms.storecrf');
Route::get('clients/{client}/forms/{formid}/generatecrf','ClientController@generateCrfForm')->name('forms.generatecrf');
Route::get('clients/{client}/forms/upload','ClientController@saveCrfForm')->name('forms.upload');
Route::get('clients/{client}/forms/delete/{formid}','ClientController@deleteCrfForm')->name('crfforms.destroy');
Route::get('clients/{client_id}/completed/{step_id}/{newdate}','ClientController@complete')->name('clients.complete');
Route::get('clients/{client_id}/uncompleted/{step_id}','ClientController@uncomplete')->name('clients.uncomplete');
Route::get('clients/{client_id}/changecompleted/{step_id}/{newdate}','ClientController@changecomplete')->name('clients.changecomplete');
Route::post('clients/{client}/sendnotification/{activity?}','ClientController@sendNotification')->name('clients.sendnotification');
Route::post('clients/{client}/sendtemplate/{activity?}','ClientController@sendTemplate')->name('clients.sendtemplate');
Route::post('clients/{client}/senddocument/{activity?}','ClientController@sendDocument')->name('clients.senddocument');
Route::get('clients/{client}/viewtemplate/{template?}','ClientController@viewTemplate')->name('clients.viewtemplate');
Route::get('clients/{client}/viewdocument/{document?}','ClientController@viewDocument')->name('clients.viewdocument');
Route::put('clients/{client}/follow','ClientController@follow')->name('clients.follow');
Route::get('clients/{client}/activityprogress/{process}/{step}','ClientController@activityProgress')->name('clients.activityprogress');
Route::post('clients/{client}/storecomment','ClientController@storeComment')->name('clients.storecomment');
Route::post('clients/{client}/progressing','ClientController@storeProgressing')->name('clients.progressing');
Route::post('clients/{client}/qa','ClientController@storeQA')->name('clients.qa');
Route::post('clients/{client}/qacomplete','ClientController@completeQA')->name('clients.qacomplete');
Route::post('clients/{client}/qaprod','ClientController@storeProd')->name('clients.qaprod');
Route::post('clients/{client}/approval','ClientController@approval')->name('clients.approval');
Route::post('clients/{client}/senddocuments/{activity?}','ClientController@sendDocuments')->name('clients.senddocuments');
Route::get('clients/{client}/delete','ClientController@destroy')->name('clients.delete');
Route::get('clients/{clientid}/show/{process}/{step}','ClientController@show')->name('clients.show');
Route::get('clients/{clientid}/restore','ClientController@restore')->name('clients.restore');
Route::post('clients/{clientid}/addcomment/{activityid}','ActivityCommentController@addComment');
Route::post('clients/{clientid}/showcomment/{activityid}','ActivityCommentController@showComment');
Route::post('clients/deletecomment/{commentid}','ActivityCommentController@destroyComment');
Route::post('clients/editcomment/{commentid}','ActivityCommentController@editComment');
Route::post('clients/updatecomment/{commentid}','ActivityCommentController@updateComment');
Route::get('client/{client}/basket/{process}/{step}', 'ClientBasketController@show')->name('client.basket');
Route::any('client/{client}/progress/{process}/{step}', 'ClientBasketController@clientProgress')->name('client.progress');
Route::post('client/{client}/storeprogress/{process}/{step}', 'ClientBasketController@clientStoreProgress')->name('client.storeprogress');
Route::post('client/{client}/sendclientemail', 'ClientBasketController@sendClientEmail');
Route::get('client/{client}/emailqr', 'ClientController@sendQr')->name('client.emailqr');

app/ClientForm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ClientForm extends Model
{
    protected $table = 'client_forms';
    protected $touches = ['client'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function type()
    {
        return pathinfo($this->file, PATHINFO_EXTENSION);
    }

    public function size()
    {
        try {
            $bytes = Storage::size('crf/' . $this->file);
            $i = floor(log($bytes, 1024));
            return round($bytes / pow(1024, $i), [0, 0, 2, 2, 3][$i]) . ['B', 'kB', 'MB', 'GB', 'TB'][$i];
        } catch (\Exception $e) {
            return "LStat";
        }
    }

    public function client()
    {
        return $this->belongsTo('App\Client','client_id');
    }
}

resources/views/clients/activityprogress.blade.php
@extends('clients.show')

@section('tab-content')
    <div class="col">
        <div class="process_step" id="activity_progress_{{$step->id}}">
            {{--<h3 id="{{$step->id}}" class="p-2" style="background-color: {{$client->process->getStageHex($step->name)}};width:100%;">{{$step->name}}</h3>--}}
            <h3 id="{{$step->id}}" class="p-2" style="width:100%;">{{$activity_progress_name}}</h3>
            <div style="padding: 0.5rem"><strong>Completed activities:</strong>
            <ul>
                {!! $completed !!}
            </ul>
                <strong>Not completed activities:</strong>
            <ul>
                {!! $not_completed !!}
            </ul>
            <a href="{{route('clients.progress', $client->id)}}/{{$step->process_id}}/{{$step->id}}">Back to form</a></div>
        </div>
    </div>
@endsection
@section('extra-js')
    {{--<script>
        showActivityProgress({{$id}});
        
        function showActivityProgress(id){
            $("#activity_progress_"+id).show();
        }
    </script>--}}
@endsection

resources/views/clients/amlreports.blade.php
@extends('layouts.app')

@section('title') Clients @endsection

@section('header')
    <h1><i class="fa fa-address-card-o"></i> @yield('title')</h1>
    <a href="{{route('clients.create')}}" class="btn btn-outline-light float-right"><i class="fa fa-plus"></i> Client</a>
@endsection

@section('content')
    <form class="form-inline mt-3">
        Show &nbsp;
        {{Form::select('s',['all'=>'All','mine'=>'My','country'=>'Country wide','region'=>'Region wide','office'=>'Office wide'],old('selection'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('p',$processes ,old('p'),['class'=>'form-control form-control-sm'])}}
        &nbsp; for &nbsp;
        {{Form::select('c',['all'=>'All completions','no'=>'Not completed','yes'=>'Completed'],old('c'),['class'=>'form-control form-control-sm'])}}
        &nbsp; in &nbsp;
        {{Form::select('step',$steps ,old('step'),['class'=>'form-control form-control-sm'])}}
        &nbsp; from &nbsp;
        {{Form::date('f',old('f'),['class'=>'form-control form-control-sm'])}}
        &nbsp; to &nbsp;
        {{Form::date('t',old('t'),['class'=>'form-control form-control-sm'])}}
        &nbsp; matching &nbsp;
        <div class="input-group input-group-sm">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            {{Form::text('q',old('query'),['class'=>'form-control form-control-sm','placeholder'=>'Search...'])}}
        </div>
        <button type="submit" class="btn btn-sm btn-secondary ml-2 mr-2"><i class="fa fa-search"></i> Search</button>
        <a href="{{route('clients.index')}}" class="btn btn-sm btn-outline-info"><i class="fa fa-eraser"></i> Clear</a>
    </form>

    <hr>

    <div class="table-responsive">
        <table class="table table-bordered table-sm table-hover">
            <thead class="thead-light">
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
                <th>Process</th>
                <th>Created</th>
                <th>Completed</th>
                <th><abbr title="Days taken to complete a clients process.">Duration</abbr></th>
                <th>Step</th>
                <th>User</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients as $client)
                <tr>
                    <td><a href="{{route('clients.show',$client)}}">{{$client->company}}</a></td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->contact}}</td>
                    <td>{{$client->process->name}}</td>
                    <td>{{$client->created_at}}</td>
                    <td>{{!is_null($client->completed_at) ? $client->completed_at->toDateString() : ''}}</td>
                    <td>{{$client->completed_days}}</td>
                    <td>{{$client->getCurrentStep()->name}}</td>
                    <td><a href="{{route('profile',$client->introducer)}}" title="{{$client->introducer->name()}}"><img src="{{route('avatar',['q'=>$client->introducer->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="Avatar"/></a></td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center"><small class="text-muted">No clients match those criteria.</small></td></td>
                </tr>
            @endforelse
            </tbody>

        </table>
    </div>

    <small class="text-muted">Found <b>{{sizeof($clients)}}</b> clients matching those criteria.</small>
@endsection

resources/views/clients/create.blade.php
@extends('adminlte.default')

@section('title')
    Capture Visit
@endsection

@section('header')
    <div class="container-fluid container-title">
        <h3>@yield('title')</h3>
        @auth
        <a href="{{route('clients.index')}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
        @endauth
    </div>
@endsection

@section('content')
    <div class="container-fluid">
        @if(isset($forms) && count($forms) > 0)
        <nav class="tabbable">
            <div class="nav nav-pills">
                <a class="nav-link active show" id="default-tab" data-toggle="tab" href="#default" role="tab" aria-controls="default" aria-selected="false">Default</a>
                @foreach($forms as $key =>$value)
                    @foreach($value as $section =>$v1)
                        <a class="nav-link" id="{{strtolower(str_replace(' ','_',$section))}}-tab" data-toggle="tab" href="#{{strtolower(str_replace(' ','_',$section))}}" role="tab" aria-controls="{{strtolower(str_replace(' ','_',$section))}}" aria-selected="true">{{$section}}</a>
                    @endforeach
                @endforeach
            </div>
        </nav>
        @endif
        {{Form::open(['url' => route('clients.store'), 'method' => 'post','autocomplete'=>'off'])}}
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active p-3" id="default" role="tabpanel" aria-labelledby="default-tab">
                <input type="hidden" name="office_id" value="{{(isset($office_id) ? $office_id : auth()->user()->office()->id)}}" />
                <div class="row mt-3">
                    <div class="col-lg-12">
                        <div class="form-group">
                            {{Form::label('first_name', 'Name')}}
                            {{Form::text('first_name',old('first_name'),['class'=>'form-control form-control-sm'. ($errors->has('first_name') ? ' is-invalid' : ''),'placeholder'=>'First Name'])}}
                            @foreach($errors->get('first_name') as $error)
                                <div class="invalid-feedback">
                                    {{$error}}
                                </div>
                            @endforeach
                        </div>

                        <div class="form-group">
                            {{Form::label('email', 'Email')}}
                            {{Form::email('email',old('email'),['class'=>'form-control form-control-sm'. ($errors->has('email') ? ' is-invalid' : ''),'placeholder'=>'Email'])}}
                            @foreach($errors->get('email') as $error)
                                <div class="invalid-feedback">
                                    {{$error}}
                                </div>
                            @endforeach
                        </div>

                        <div class="form-group">
                            {{Form::label('contact', 'Cellphone Number')}}
                            {{Form::text('contact',old('contact'),['class'=>'form-control form-control-sm'. ($errors->has('contact') ? ' is-invalid' : ''),'placeholder'=>'Contact Number'])}}
                            @foreach($errors->get('contact') as $error)
                                <div class="invalid-feedback">
                                    {{$error}}
                                </div>
                            @endforeach
                        </div>

                        <div class="form-group">
                            {{Form::label('accompanied', 'Are you accompanied by children?')}}
                            <div class="form-group">
                                <label class="radio-inline"><input type="radio" name="accompanied" value="1"><span class="ml-2">Yes</span></label>
                                <label class="radio-inline ml-3"><input type="radio" name="accompanied" value="0"><span class="ml-2">No</span></label>
                                @foreach($errors->get('accompanied') as $error)
                                    <div class="invalid-feedback">
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        </div>

                        <div class="form-group accompanied_before" style="display: none;">
                            {{Form::label('accompanied_before', 'Have you been accompanied by any of these children before?')}}
                            <div class="form-group">
                                <label class="radio-inline"><input type="radio" name="accompanied_before" value="1"><span class="ml-2">Yes</span></label>
                                <label class="radio-inline ml-3"><input type="radio" name="accompanied_before" value="0"><span class="ml-2">No</span></label>
                                @foreach($errors->get('accompanied_before') as $error)
                                    <div class="invalid-feedback">
                                        {{$error}}
                                    </div>
                                @endforeach
                            </div>
                        </div>

                        <div class="form-group nr_accompanied" style="display: none;">
                            {{Form::label('nr_accompanied', 'Number of accompanying children')}}
                            <select name="nr_accompanied" class="chosen-select form-control form-control-sm">
                                <option value="0">Please Select</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            </select>
                            @foreach($errors->get('nr_accompanied') as $error)
                                <div class="invalid-feedback">
                                    {{$error}}
                                </div>
                            @endforeach
                        </div>

                    </div>
                </div>

            </div>

        </div>
            <div class="blackboard-fab mb-3">
                <button type="submit" class="btn btn-info btn-lg process-submit"><i class="fa fa-arrow-right"></i><span class="save_span">Next</span></button>
            </div>
        {{Form::close()}}
    </div>

@endsection
@section('extra-css')
    <link rel="stylesheet" href="{{asset('chosen/chosen.min.css')}}">
    <style>
        a:focus{
            outline:none !important;
            border:0px !important;
        }

        .activity a{
            color: rgba(0,0,0,0.5) !important;
        }

        .activity a.dropdown-item {
            color:#212529 !important;
        }

        .btn-comment{
            padding: .25rem .25rem;
            font-size: .575rem;
            line-height: 1;
            border-radius: .2rem;
        }

        .modal-dialog {
            max-width: 700px;
            margin: 1.75rem auto;
        }

        .chosen-container, .chosen-container-multi{
            width:100% !important;
        }

        .chosen-container, .chosen-container-multi{
            line-height: 30px;
        }

        .modal-open .modal{
            padding-right: 0px !important;
        }

        .progress { position:relative; width:100%; border: 1px solid #7F98B2; padding: 1px; border-radius: 3px; display:none; }
        .bar { background-color: #B4F5B4; width:0%; height:25px; border-radius: 3px; }
        .percent { position:absolute; display:inline-block; top:3px; left:48%; color: #7F98B2;}
    </style>
@endsection
@section('extra-js')
    <script>

        $(document).ready(function(){
            $('input[type=radio][name=accompanied]').on('click',function() {
                if (this.value === '1') {
                    $('.accompanied_before').show();
                    $('.nr_accompanied').show();
                }
                else if (this.value === '0') {
                    $('.accompanied_before').hide();
                    $('.nr_accompanied').hide();
                }
            });
        })

    </script>
@endsection

resources/views/clients/documents.blade.php
@extends('clients.show')

@section('tab-content')
    <div class="col-lg-12">

        <a href="{{route('documents.create',['client'=>$client->id,'process_id'=>$process_id,'step_id'=>$step["id"]])}}" class="btn btn-outline-primary btn-sm"><i class="fa fa-plus"></i> Document</a>

        <div class="table-responsive mt-3">
            <table class="table table-bordered table-sm table-hover">
                <thead class="btn-dark">
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Size</th>
                    <th>Uploader</th>
                    <th>Added</th>
                    <th class="last">Action</th>
                </tr>
                </thead>
                <tbody>
                @forelse($client->documents as $document)
                    <tr>
                        <td><a href="{{route('document',['q'=>$document->file])}}" target="_blank">{{$document->name}}</a></td>
                        <td>{{$document->type()}}</td>
                        <td>{{$document->size()}}</td>
                        <td>@if($document->user_id != 0) <a href="{{route('profile',$document->user)}}" title="{{$document->user->name()}}"><img src="{{route('avatar',['q'=>$document->user->avatar])}}" class="blackboard-avatar blackboard-avatar-inline" alt="{{$document->user->name()}}"/></a> @else Uploaded by client @endif</td>
                        <td>{{$document->created_at->diffForHumans()}}</td>
                        <td class="last">
                            <a href="{{route('documents.edit',['document_id'=>$document,'client'=>$client->id,'process_id'=>$process_id,'step_id'=>$step["id"]])}}" class="btn btn-success btn-sm">Edit</a>
                            {{ Form::open(['id' => 'documentDelete','method' => 'DELETE','route' => ['documents.destroy','id'=>$document->id,'client_id' =>$document->client_id,'process_id'=>$process_id,'step_id'=>$step["id"]],'style'=>'display:inline']) }}
                            <a href="#" class="delete deleteDoc btn btn-danger btn-sm">Delete</a>
                            {{Form::close() }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="100%" class="text-center">No documents match those criteria.</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection
@section('extra-css')
    <link rel="stylesheet" href="{{asset('chosen/chosen.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <style>
        a:focus{
            outline:none !important;
            border:0px !important;
        }

        .activity a{
            color: rgba(0,0,0,0.5) !important;
        }

        .activity a.dropdown-item {
            color:#212529 !important;
        }

        .btn-comment{
            padding: .25rem .25rem;
            font-size: .575rem;
            line-height: 1;
            border-radius: .2rem;
        }

        .modal-dialog {
            max-width: 700px;
            margin: 1.75rem auto;
            min-width: 500px;
        }

        .modal .chosen-container, .modal .chosen-container-multi{
            width:98% !important;
        }

        .chosen-container, .chosen-container-multi{
            line-height: 30px;
        }

        .modal-open .modal{
            padding-right: 0px !important;
        }

        .progress { position:relative; width:100%; border: 1px solid #7F98B2; padding: 1px; border-radius: 3px; display:none; }
        .bar { background-color: #B4F5B4; width:0%; height:25px; border-radius: 3px; }
        .percent { position:absolute; display:inline-block; top:3px; left:48%; color: #7F98B2;}
    </style>
@endsection

resources/views/clients/show.blade.php
@extends('adminlte.default')

@section('title') {{($client->company == '' || $client->company == 'N/A' || $client->company == 'n/a' ? $client->first_name.' '.$client->last_name : $client->company )}} @endsection

@section('header')
    <div class="container-fluid container-title form-inline">
        <div class="col-sm-4">
            <h3 class="form-inline">@yield('title')</h3>
        </div>
        @auth
        <div class="col-sm-7 process-dropdown" style="padding-top: 0px;">
        {{--@if(isset($view_process_dropdown) && isset($client))
                <input type="hidden" value="{{$client->id}}" id="client_id" />
                <label class="float-left" style="margin-right: 10px;padding-top:5px;">View Application</label> <select class="chosen-select form-control form-control-sm float-left ml-3" id="viewprocess">
                @forelse($view_process_dropdown as $k=>$v)
                        <optgroup label="{{$k}}">
                        @foreach($v as $key=>$value)
                            <option value="{{$value['id']}}" {{(isset($process_id) && $process_id == $value['id'] ? 'selected' : '')}}>{{$value["name"]}}</option>
                        @endforeach
                        </optgroup>
                @empty
                    <option value="">There are no applications available for this client.</option>
                @endforelse
            </select>
        @else
            @forelse(auth()->user()->office()->processes->first()->steps as $step)
                <div class="col-lg blackboard-step-{{$step->id}}">
                    {{$step->name}}
                </div>
            @empty
                <p>There are no applications available for this client.</p>
            @endforelse
        @endif--}}
        </div>
        <div class="col-sm-1 back-btn">
        <a href="{{(isset($path) && $path == 1 ? $path_route : route('clients.index'))}}" class="btn btn-dark btn-sm float-right"><i class="fa fa-caret-left"></i> Back</a>
        </div>
        @endauth
    </div>
@endsection

@section('content')
<div class="container-fluid">
    @include('clients.process')
    @auth
    <ul class="nav nav-tabs nav-fill mt-3">
        <li class="nav-item">
            <a class="nav-link {{active('clients.show','active')}}" href="{{route('clients.show',[$client,$process_id,$step["id"]])}}" >Details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{(\Request::is('clients/*/progress/*') ? 'active' : '')}}" href="{{route('clients.progress',$client)}}/{{$process_id}}/{{$step["id"]}}">Visit</a>
        </li>
        {{--<li class="nav-item">
            <a class="nav-link {{active('clients.documents','active')}}" href="{{route('clients.documents',[$client,$process_id,$step["id"]])}}">Documents</a>
        </li>
            <li class="nav-item">
                <a class="nav-link {{active('client.basket','active') || active('client.progress','active')}}" href="{{route('client.basket',[$client,$process_id,$step["id"]])}}">Client Basket</a>
            </li>--}}
    </ul>
    @endauth

<div class="row m-0 pb-0 border-0 activity-container">

@yield('tab-content')

</div>
</div>
@endsection